- hosts: all
  remote_user: ubuntu
  become: yes
  vars_prompt:
    - name: name
      prompt: "please enter you'r name"
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: copy configuration of nginx
      template:
          src: index.j2
          dest: /var/www/html/index.nginx-debian.html
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
