- hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    - test: test

  vars_prompt:
    - name: name
      prompt: "Please Enter Your Name: "
      private: no

  tasks: 
    - name: install nginx
      apt: 
        name: nginx
        state: present
      notify: restart nginx

    - name: create directory
      file: 
        path: "{{ test }}"
        state: directory
      when: test == "jenkins"

    - name: create list of users
      user:
        name: "{{ item }}"
      
      with_items:
        - ahmed
        - mohamed
        - mostafa

    - name: run ls
      command: "ls"
      register: cmd_output
      notify: restart nginx

    - name: print output
      debug:
        var: cmd_output.stdout

    - name: copy template
      template: 
        src: mytemplate.j2
        dest: mytemplate.html


      
      
  

# - hosts: localhost
#   tasks: 
#     - name: run ls command
#       command: "ls"

  handlers:
    - name: restart nginx
      service: 
        name: nginx
        state: restarted



