- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: update apt
      apt: 
        update_cache: yes

    - name: create dir
      file:
        name: jenkins_home
        state: directory
        mode: 0777

    - name: install openjdk
      apt:
        name: openjdk-8-jdk
        state: present

    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
     	
     
